name: video_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.4
  retrofit: 1.3.4
  provider: ^5.0.0
  kiwi: 2.1.1
  pull_to_refresh: ^1.5.6
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6
  flare_flutter: ^1.6.1
  path_provider: ^1.3.0
  permission_handler: ^5.1.0+2
  unique_identifier: ^0.0.3
  flutter_spinkit: ^4.0.0
  flushbar: 1.10.4
  flutter_tags: ^0.4.9+1
  flutter_facebook_auth: ^2.0.2+1
  apple_sign_in: ^0.1.0
  http_proxy: ^1.1.0
  agora_rtc_engine: ^4.0.6
  agora_rtm: ^0.9.14
  sticky_headers: ^0.2.0
  intl: ^0.16.1
  lazy_loading_list: ^1.0.1
  in_app_purchase: 0.5.2
  flutter_tindercard: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  kiwi_generator: 2.1.1
  build_runner: any


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/Common/
    - assets/Splash/
    - assets/json/
    - assets/Language/
    - assets/Login/
    - assets/Home/
    - assets/Tab/
    - assets/Temp/
    - assets/Chat/
    - assets/Profile/
    - assets/Vip/
    - assets/Video/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.TTF
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.TTF
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.TTF
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.TTF
          weight: 400
        - asset: assets/fonts/Montserrat-Light.TTF
          weight: 300
