name: video_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.6
  provider: ^6.0.0
  table_calendar: ^3.0.6
  kiwi: ^3.0.0
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.7
  flare_flutter: ^3.0.2
  image_cropper: ^2.0.3
  permission_handler: ^8.1.6
  flutter_spinkit: ^5.1.0
  another_flushbar: ^1.10.24
  flutter_facebook_auth: ^3.5.1
  sign_in_with_apple: ^3.0.0
  # http_proxy: ^1.1.0
  agora_rtc_engine: ^5.2.0
  agora_rtm: ^1.0.0
  sticky_headers: ^0.2.0
  intl: ^0.17.0
  lazy_loading_list: ^1.0.1
  # in_app_purchase: ^1.0.8
  flutter_inapp_purchase: 5.1.2
  # in_app_purchase: any
  multi_image_picker2: ^5.0.02

  flutter_image_compress: ^1.1.0
  country_picker: ^2.0.8
  rate_my_app: ^1.1.1
  package_info: ^2.0.2
  google_sign_in: ^5.1.0
  flutter_keyboard_visibility: ^5.0.3
  device_info: ^2.0.2
  socket_io_client: ^1.0.1
  firebase_performance: ^0.7.0+9

  firebase_messaging: ^10.0.7
  firebase_core: ^1.6.0
  flutter_local_notifications: ^8.2.0
  circular_countdown_timer: ^0.2.0
  assets_audio_player: ^3.0.3+7
  dio: ^4.0.0
  simple_tags: ^0.0.4
  firebase_crashlytics: ^2.2.1
  firebase_analytics: ^8.3.4
  pull_to_refresh: ^2.0.0
  url_launcher: any
  camera: any

  check_vpn_connection: any
  appsflyer_sdk: ^6.5.2+2
  flutter_dotenv: ^5.0.2
  flutter_absolute_path:
    path: ./flutter_absolute_path
  freshchat_sdk:
    path: ./freshchat-flutter-sdk-main


dev_dependencies:
  flutter_test:
    sdk: flutter
  kiwi_generator: ^3.0.0-nullsafety-generator.1
  build_runner: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/Common/
    - assets/Splash/
    - assets/json/
    - assets/Login/
    - assets/Home/
    - assets/Tab/
    - assets/Chat/
    - assets/Profile/
    - assets/Vip/
    - assets/Video/
    - assets/Audio/
    - assets/Onboarding/
    - assets/Verification/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.TTF
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.TTF
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.TTF
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.TTF
          weight: 400
        - asset: assets/fonts/Montserrat-Light.TTF
          weight: 300
